branches: [master, test]
matrix:
  include:
  - HOST: libtest1.csc.fi
    USER: aleph
    DIRECTORY: /exlibris/aleph/u23_3/alephe/apache/htdocs/aleph-own-auth-api/app
    TAR_EXEC: /usr/sfw/bin/gtar
    INSTANCE: test
  - HOST: alina.csc.fi
    USER: aleph
    DIRECTORY: /exlibris/aleph/u23_3/alephe/apache/htdocs/aleph-own-auth-api/app
    TAR_EXEC: /usr/sfw/bin/gtar
    INSTANCE: production
pipeline:
# Test
  test-deploy:
    image: quay.io/natlibfi/drone-plugin-scp
    host: ${HOST}
    username: ${USER}
    target: ${DIRECTORY}
    source: ['.']
    rm: true
    tar_exec: ${TAR_EXEC}
    secrets:
    - source: ssh_key_${HOST}
      target: ssh_key
    when:
      branch: test
      matrix:
        INSTANCE: test
  test-install-deps:
    image: quay.io/natlibfi/drone-plugin-ssh
    host: ${HOST}
    username: ${USER}
    script:
    - cd ${DIRECTORY}
    - curl -L -O https://github.com/NatLibFi/aleph-conf-parser/archive/master.zip
    - unzip master.zip
    - mv aleph-conf-parser-master aleph_conf_parser
    - rm master.zip
    secrets:
    - source: ssh_key_${HOST}
      target: ssh_key
    when:
      branch: test
      matrix:
        INSTANCE: test
# Production
  prod-deploy:
    image: quay.io/natlibfi/drone-plugin-scp
    host: ${HOST}
    username: ${USER}
    target: ${DIRECTORY}
    source: ['.']
    rm: true
    tar_exec: ${TAR_EXEC}
    secrets:
    - source: ssh_key_${HOST}
      target: ssh_key
    when:
      branch: master
      matrix:
        INSTANCE: production
  prod-install-deps:
    image: quay.io/natlibfi/drone-plugin-ssh
    host: ${HOST}
    username: ${USER}
    script:
    - cd ${DIRECTORY}
    - curl -L -O https://github.com/NatLibFi/aleph-conf-parser/archive/master.zip
    - unzip master.zip
    - mv aleph-conf-parser-master aleph_conf_parser
    - rm master.zip
    secrets:
    - source: ssh_key_${HOST}
      target: ssh_key
    when:
      branch: master
      matrix:
        INSTANCE: production
